theme: jekyll-theme-merlot
title: Welcome to a Two week FDP on "Outcome Based Education using Moodle"
description: by 
               Hardeep Singh Rai
               Amit Kamra
               Ranjodh Kaur 
               Yuvraj Singh
